### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by marinkaz** [comment]
Try to complete the movie ratings matrix (relation "rate") and show it in a Data Table. The matrix appears sparse and contain missing values. Completed relations should be dense.

**Comment by kernc** [comment]
Yeah, that's because the input relation is an **unmasked `ndarray`** and [thus returned as is](https://github.com/kernc/orange3-datafusion/blob/fixups/orangecontrib/datafusion/widgets/owmeanfuser.py#L53). No masked arrays come out of `movielens.movie_user_matrix()`. ~~Perhaps @alekdimi knows what needs to be done?~~

Please kindly see if the last commit fixes it. :smile:

**Comment by marinkaz** [comment]
Thanks, it works now. In general, we would like completed relations to be dense. If there are some unknown/invalid values in the non-masked parts they should be filled as well. You can use the `numpy.ma.masked_invalid` function.

**Comment by kernc** [comment]
Got it. Fixed.

**Pull request merged**
